services:
  - type: web
    name: cibdi_project
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    branch: main
    autoDeploy: true